import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Reda coffe store</title>
        <meta name="description" content="Generated by Reda the coffe maker" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className='text-center md:text-6xl mb-5 xxs:text-3xl'>
          <span className="hand">👋</span> Hello I'm Reda
        </h1>
        <p className='text-center w-4/5 font-mono'> So you clicked on my profile link, it is a great honor to have you here.
          Unfotunatly there is no coffee here yet.<br />
        </p>
        <p className='text-center w-4/5 font-mono'> <span className='text-red-700'>WARNING!:</span> The person you are about to communicate with in case you did so is very Abstract, weird and unbiased. So, I hope you did not change your mind. Looking forward to talk to you.</p>


      </main>

      <footer className={styles.footer}>
        <p>
          © 2022 Reda Coffee Company
        </p>
      </footer>
    </div>
  )
}
